spring:
  application:
    name: client-test
#服务端口
server:
  port: 10212
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10211/eureka/
  instance:
    prefer-ip-address: true